const SET_COMPANIES = 'SET_COMPANIES';
const SET_INVOICES = 'SET_COMPANIES';
const CLEAR_DB = 'CLEAR_DB';
const SET_DISPLAY_MODAL = 'SET_DISPLAY_MODAL';

export { SET_COMPANIES, SET_INVOICES, CLEAR_DB, SET_DISPLAY_MODAL };
