const SET_COMPANIES = 'SET_COMPANIES';
const SET_INVOICES = 'SET_INVOICES';
const CLEAR_DB = 'CLEAR_DB';
const SET_VIEW_MODE = 'SET_VIEW_MODE';

export { SET_COMPANIES, SET_INVOICES, CLEAR_DB, SET_VIEW_MODE };
